#!/bin/bash

## Colors !

red=$(tput setaf 1)
blue=$(tput setaf 4)
white=$(tput setaf 7)

## Help menu

USAGE="$(basename "$0"): ./crunner filename.extension -- compiles and executes the executable

"

while getopts f:h input
do
case "${input}"
in
h) echo "${USAGE}" && exit 0 ;;
*)  echo
	echo "Invalid option: -$input" && exit 0 ;;
esac
done

run(){
	if [[ "${FILE#*.}" == c ]]; then

    	gcc -Wall -g "$FILE" -o "${FILE%%.*}.out"
    	rm -rf ./"${FILE%%.*}".dSYM
    	./"${FILE%%.*}.out"

	elif [[ "${FILE#*.}" == cpp ]]; then

    	g++ -Wall -g "$FILE" -o "${FILE%%.*}.out"
    	rm -rf ./"${FILE%%.*}".dSYM
    	./"${FILE%%.*}.out"

	else

    	ERROR="$(echo "${white}Unsupported filetype specified.")"

    	echo "${red}ERROR:" "$ERROR"
    	echo "${blue}Exitting crunner.."

	fi
}

## Logic for checking backslash, enabling you to execute the code from anywhere else

FILE_LOCATION="$1"

if [[ "$FILE_LOCATION" != */* ]]; then
	FILE="$FILE_LOCATION"
	run
else
	LOCATION="${FILE_LOCATION%/*}"
	FILE_NAME="${FILE_LOCATION##*/}"
	FILE="$FILE_NAME"

	cd "$LOCATION" || exit
	run
fi
